servers:
    errors:
        #kalo error servernya bakal send semua datanya
        include-message: always
        include-binding-errors: always
spring:
    datasoure:
    password:
    #Url TBA
    url: 
    username:
jpa:
    #pas servernya mulai table bakan auto dibikin
    #pas server stop table bakal auto di drop
    #buat development, kalo udh mau asli diapus
    hibernate:
        ddl-auto: create-drop

    #other info kyknya buat setting sql tapi gadikasih tau di tutorial :(
    properties: 
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true